Tipo de comida
eliiasribeiro/comidinhas pull request #1
Opened 2021-03-16 17:52 UTC by eliiasribeiro

2021-03-19 00:28 UTC, alexandreaquiles requested changes

2021-03-19 00:28 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinha/tipoComida/EditarTipoCozinhaValidator.java
> +        if (tipoComidaRepository.existsByNome(tipoComidaFormEditar.getNome())){
BUG: :beetle:  Acho que se tentar editar um nome mas não mudar nada, vai dar pau: o nome já existe no BD. Precisa ver se há alguém com o mesmo nome mas com um id diferente.

Testa com o Postman pra ver se dá pau. Se der, cria um teste pro validator que falha e depois corrige!

2021-03-19 00:28 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinha/tipoComida/TipoComidaControllerTest.java
> +    void deve_retornar_a_mensagem_de_erro_quando_ja_existe_o_nome() throws Exception {
Falta de consistência: o teste fala de "mensagem de erro", mas só checa o status.

Acho que só verificar status tá ótimo. É mais o nome do método.

2021-03-22 18:59 UTC, alexandreaquiles commented
Tava pensando aqui, @eliiasribeiro 

No card, eu uso o termo "Tipo de Cozinha". Mas você usou "Tipo de Comida" no código.

Considerando aquela ideia do DDD de [Ubiquitous Language](https://martinfowler.com/bliki/UbiquitousLanguage.html), em que a linguagem de negócio tem que estar representada no código, acho que deveria ser usado o termo "Tipo de Cozinha" no código.

O que você acha?

2021-03-22 19:51 UTC, eliiasribeiro commented
> Tava pensando aqui, @eliiasribeiro
> 
> No card, eu uso o termo "Tipo de Cozinha". Mas você usou "Tipo de Comida" no código.
> 
> Considerando aquela ideia do DDD de [Ubiquitous Language](https://martinfowler.com/bliki/UbiquitousLanguage.html), em que a linguagem de negócio tem que estar representada no código, acho que deveria ser usado o termo "Tipo de Cozinha" no código.
> 
> O que você acha?

Por mim de boas, pego pra renomear pra tipo de cozinha

2021-03-22 19:57 UTC, alexandreaquiles commented
> > Tava pensando aqui, @eliiasribeiro
> > No card, eu uso o termo "Tipo de Cozinha". Mas você usou "Tipo de Comida" no código.
> > Considerando aquela ideia do DDD de [Ubiquitous Language](https://martinfowler.com/bliki/UbiquitousLanguage.html), em que a linguagem de negócio tem que estar representada no código, acho que deveria ser usado o termo "Tipo de Cozinha" no código.
> > O que você acha?
> 
> Por mim de boas, pego pra renomear pra tipo de cozinha

Boa! Eu sei que é um trabalho chato, mas faz sentido, né? Manda brasa! :rocket:

2021-03-23 10:58 UTC, eliiasribeiro commented
> > > Tava pensando aqui, @eliiasribeiro
> > > No card, eu uso o termo "Tipo de Cozinha". Mas você usou "Tipo de Comida" no código.
> > > Considerando aquela ideia do DDD de [Ubiquitous Language](https://martinfowler.com/bliki/UbiquitousLanguage.html), em que a linguagem de negócio tem que estar representada no código, acho que deveria ser usado o termo "Tipo de Cozinha" no código.
> > > O que você acha?
> > 
> > 
> > Por mim de boas, pego pra renomear pra tipo de cozinha
> 
> Boa! Eu sei que é um trabalho chato, mas faz sentido, né? Manda brasa!

@alexandreaquiles queria entregar esse card primeiro ao inves do outro pq eu buguei pra fazer algumas coisas do outro

2021-03-23 14:05 UTC, alexandreaquiles commented
> > > > Tava pensando aqui, @eliiasribeiro
> > > > No card, eu uso o termo "Tipo de Cozinha". Mas você usou "Tipo de Comida" no código.
> > > > Considerando aquela ideia do DDD de [Ubiquitous Language](https://martinfowler.com/bliki/UbiquitousLanguage.html), em que a linguagem de negócio tem que estar representada no código, acho que deveria ser usado o termo "Tipo de Cozinha" no código.
> > > > O que você acha?
> > > 
> > > 
> > > Por mim de boas, pego pra renomear pra tipo de cozinha
> > 
> > 
> > Boa! Eu sei que é um trabalho chato, mas faz sentido, né? Manda brasa!
> 
> @alexandreaquiles queria entregar esse card primeiro ao inves do outro pq eu buguei pra fazer algumas coisas do outro

Opa, @eliiasribeiro 
É uma ótima focar nesse card. Lembra daquele lema: "Pare de começar e comece a terminar"! hehe
Mais tarde conversamos sobre aquela feature.

2021-03-23 14:07 UTC, alexandreaquiles approved these changes

2021-03-23 19:21 UTC, alexandreaquiles reviewed
Alguns detalhes precisam ser corrigidos.

2021-03-24 00:19 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaControllerTest.java
> +        verify(tipoCozinhaRepository,times(1)).deleteById(1L);
Elias, eu lembrei que se usar só o `verify`, já checa que foi chamado apenas uma vez. Então, daria pra trocar para:

```suggestion
        verify(tipoCozinhaRepository).deleteById(1L);
```

2021-03-29 18:55 UTC, alexandreaquiles requested changes

2021-03-29 18:55 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Ué? Mas não íamos deixar como `400 BAD REQUEST`?

2021-03-29 18:55 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaControllerTest.java
> +@AutoConfigureMockMvc
Dá pra trocar todas essas anotações por apenas:

```suggestion
@WebMvcTest(TipoCozinhaController.class)
```

Um `@WebMvcTest` sobe o Controller, o Validator, mas não precisa de conexão com o BD.

2021-03-29 21:18 UTC, alexandreaquiles commented
Eu removeria o `ComidinhaApplicationTests` também.

2021-03-29 21:25 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Pensando melhor, você não quer criar uma exceção específica para quando o relacionamento não existe e testar ela?

2021-03-29 21:28 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaInputEditar.java
> +        if(!isNull(possivelTipoCozinha)){
Acho que esse `!isNull` não é necessário. Se alguém passar uma função vazia, deveria dar exceção.

Poderíamos fazer um:
        
```
Assert.notNull(possivelTipoCozinha, "Função não deveria ser nula");
```

2021-04-06 12:40 UTC, alexandreaquiles commented
Boa, Elias! Tava meio correria na semana passada, né? Tranquilo

Mas bora ver hoje sim. A gente avança um pouquinho nas implementações

Em ter, 6 de abr de 2021 09:39, Elias Ribeiro ***@***.***>
escreveu:

> @alexandreaquiles <https://github.com/alexandreaquiles> a gente pode ver
> isso ainda no pareamento de hj, digamos que eu full foquei nas tarefas
> essas semana, ai ate esqueci do treinamento
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eliiasribeiro/comidinhas/pull/1#issuecomment-814086615>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAB7CG47I2D66ONHLVTXACLTHL6HTANCNFSM4ZJA7BDQ>
> .
>

2021-04-07 23:07 UTC, alexandreaquiles reviewed
Deixei um comentário sobre o nome da Exception. Acho que seria bom testes de repository.

2021-04-07 23:07 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaInputEditar.java
> +                        () -> new FunctionNotFound(format("O tipo de cozinha %s informado nao existe", nome)));
Não gostei desse nome `FunctionNotFound`. O que ele quer dizer?

Acho que podia ser um nome mais específico. Que nome você daria?

2021-04-08 16:58 UTC, eliiasribeiro reviewed
> Deixei um comentário sobre o nome da Exception. Acho que seria bom testes de repository.

Os testes de repository tenho que fazer msm, tipo em relacao ao nome eu penso que e uma funcao que nao foi encontrada, mas aceito uma sugestao de nomes

2021-04-09 01:18 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaRepositoryTest.java
> +        MatcherAssert.assertThat(tipoDeCozinhas, contains(arabe,italiana,portuguesa));
A comunidade Java tem preferido usar o AssertJ.

2021-04-09 01:18 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaRepositoryTest.java
> +@AutoConfigureTestDatabase(replace= Replace.NONE)
Amanhã (09/04) vou dar uma olhada, pq com esse configuração você acaba usando o mesmo BD de dev. O ideal seria ter 2 BDs distintos. Mas preciso dar uma verificada.

2021-04-09 01:19 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaInputEditar.java
> +                        () -> new TipoDeComidaNotFound(format("O tipo de cozinha %s informado nao existe", nome)));
Esse nome ficou muito específico. Não dá pra ser menos? :joy: 

A ideia é algo como `RelationshipNotFoundException`. O que acha?

2021-04-09 21:10 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaRepositoryTest.java
> +@AutoConfigureTestDatabase(replace= Replace.NONE)
Agora que vi que já tem o db_prod e o db_test hehe
Foi mal... :grimacing:

2021-04-09 22:22 UTC, eliiasribeiro commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaInputEditar.java
> +                        () -> new TipoDeComidaNotFound(format("O tipo de cozinha %s informado nao existe", nome)));
Acho um nome bem melhor pra ser sincero

2021-04-09 22:22 UTC, eliiasribeiro commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaRepositoryTest.java
> +        tipoCozinhaRepository.save(new TipoCozinha("Portuguesa"));
boa

2021-04-12 14:48 UTC, eliiasribeiro commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaRepositoryTest.java
> +@AutoConfigureTestDatabase(replace= Replace.NONE)
entao ta certo ne?

2021-04-12 15:47 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorHandler.java
> +    }
Opa, @eliiasribeiro 

Acho que você esqueceu de fazer o push dessa classe. Ainda tá usando a `FunctionNotFound` e aí tá dando erro de compilação.

2021-04-12 17:09 UTC, eliiasribeiro commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorHandler.java
> +    }
Putz acabei de arrumar, estava pelo windows porem eu mandei o push so que pediu pra configurar o git e eu acabei esquecendo

2021-04-13 01:28 UTC, alexandreaquiles requested changes
Quase perfeito. Só 2 construtores que acho que são desnecessários no momento.

2021-04-13 01:28 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/exception/RelationshipNotFoundException.java
> +    }
Acho que não precisa desse construtor.

2021-04-13 01:28 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/FieldErrorOutputDto.java
> +    FieldErrorOutputDto() { }
Acho que não precisa desse construtor.

2021-04-15 15:24 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaRepositoryTest.java
> +@AutoConfigureTestDatabase(replace= Replace.NONE)
opa, tá sim!

2021-04-15 16:51 UTC, alexandreaquiles requested changes

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/EditarTipoCozinhaValidator.java
> +    TipoCozinhaRepository tipoCozinhaRepository;
Aqui, o atributo poderia ser `private final`:

```suggestion
    private final TipoCozinhaRepository tipoCozinhaRepository;
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/EditarTipoCozinhaValidatorTest.java
> +    public void setup(){
O `setup` não precisa ser público.

```suggestion
    void setup(){
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/FieldErrorOutputDto.java
> +    private String message;
A classe não precisa ser pública e os atributos podem ser final.

```suggestion
class FieldErrorOutputDto {

    private final String field;
    private final String message;
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorsOutputDto.java
> +    private List<FieldErrorOutputDto> fieldErrors = new ArrayList<>();
A classe não precisa ser pública e os atributos podem ser final.

```suggestion
class ValidationErrorsOutputDto {

    private final List<String> globalErrorMessages = new ArrayList<>();
    private final List<FieldErrorOutputDto> fieldErrors = new ArrayList<>();
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorsOutputDto.java
> +    }
Esses métodos não precisam ser públicos mas os getters precisam.

```suggestion
    void addError(String message) {
        globalErrorMessages.add(message);
    }

    void addFieldError(String field, String message) {
        FieldErrorOutputDto fieldError = new FieldErrorOutputDto(field, message);
        fieldErrors.add(fieldError);
    }
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/NovoTipoCozinhaValidator.java
> +    TipoCozinhaRepository tipoCozinhaRepository;
Dependência como private e final.

```suggestion
    private final TipoCozinhaRepository tipoCozinhaRepository;
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/test/java/br/com/caelum/comidinhas/tipoCozinha/NovoTipoCozinhaValidatorTest.java
> +    public void setup(){
O método `setup` não precisa ser público.

```suggestion
    void setup(){
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaController.java
> +    final TipoCozinhaRepository tipoCozinhaRepository;
Atributo de dependência como private e final (já estava).

```suggestion
    private final TipoCozinhaRepository tipoCozinhaRepository;
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorHandler.java
> +    private MessageSource messageSource;
Atributo de dependência private e final recebido no construtor, ao invés de `@Autowired`.
Onde puder injetar pelo construtor, vamos injetar.

```suggestion
    private final  MessageSource messageSource;
    
     ValidationErrorHandler(MessageSource messageSource) {
        this.messageSource = messageSource;
    }
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorHandler.java
> +    public ValidationErrorsOutputDto handleValidationErrorArgumentNotValid(MethodArgumentNotValidException exception) {
Método não precisa ser público.

Favorecemos o uso do modificador de acesso mais restrito.

```suggestion
    ValidationErrorsOutputDto handleValidationErrorArgumentNotValid(MethodArgumentNotValidException exception) {
```

2021-04-15 16:51 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/handler/validation/ValidationErrorHandler.java
> +    }
Corrigindo typo no nome do método.

Método não precisa ser público.

Favorecemos o uso do modificador de acesso mais restrito.



```suggestion
    ValidationErrorsOutputDto handleValidationErrorIllegalArgument(RelationshipNotFoundException exception) {
        ValidationErrorsOutputDto validationErrors = new ValidationErrorsOutputDto();
        validationErrors.addError(exception.getMessage());
        return validationErrors;
    }
```

2021-04-15 17:02 UTC, alexandreaquiles requested changes

2021-04-15 17:02 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaInputEditar.java
> +    private Long id;
A mensagem não foi exibida corretamente.

```
{
  "globalErrorMessages": [],
  "errors": [
    {
      "field": "id",
      "message": "{tipo.cozinha.id.not.null}"
    }
  ],
  "numberOfErrors": 1
}
```

2021-04-15 17:02 UTC, alexandreaquiles commented on src/main/java/br/com/caelum/comidinhas/tipoCozinha/TipoCozinhaInputEditar.java
> +    @Size(max = 50,message = "{tipo.cozinha.nome.size}")
Se eu envio com um nome muito grande, a mensagem não é exibida corretamente.

```
{
  "globalErrorMessages": [],
  "errors": [
    {
      "field": "nome",
      "message": "{tipo.cozinha.nome.size}"
    }
  ],
  "numberOfErrors": 1
}
```

2021-04-15 23:02 UTC, alexandreaquiles approved these changes

2021-04-15 23:03 UTC, merged